package com.squalala.dz6android.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.squalala.dz6android.greendao.Article;
import com.squalala.dz6android.greendao.Category;
import com.squalala.dz6android.greendao.CategoryArticle;

import com.squalala.dz6android.greendao.ArticleDao;
import com.squalala.dz6android.greendao.CategoryDao;
import com.squalala.dz6android.greendao.CategoryArticleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig articleDaoConfig;
    private final DaoConfig categoryDaoConfig;
    private final DaoConfig categoryArticleDaoConfig;

    private final ArticleDao articleDao;
    private final CategoryDao categoryDao;
    private final CategoryArticleDao categoryArticleDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        articleDaoConfig = daoConfigMap.get(ArticleDao.class).clone();
        articleDaoConfig.initIdentityScope(type);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        categoryArticleDaoConfig = daoConfigMap.get(CategoryArticleDao.class).clone();
        categoryArticleDaoConfig.initIdentityScope(type);

        articleDao = new ArticleDao(articleDaoConfig, this);
        categoryDao = new CategoryDao(categoryDaoConfig, this);
        categoryArticleDao = new CategoryArticleDao(categoryArticleDaoConfig, this);

        registerDao(Article.class, articleDao);
        registerDao(Category.class, categoryDao);
        registerDao(CategoryArticle.class, categoryArticleDao);
    }
    
    public void clear() {
        articleDaoConfig.getIdentityScope().clear();
        categoryDaoConfig.getIdentityScope().clear();
        categoryArticleDaoConfig.getIdentityScope().clear();
    }

    public ArticleDao getArticleDao() {
        return articleDao;
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public CategoryArticleDao getCategoryArticleDao() {
        return categoryArticleDao;
    }

}
